import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.scss";
import ThemeProvider from "./ThemeProvider";

export const metadata: Metadata = {
  title: "Sanskar - Portfolio",
  description: "Generated by create next app",
};

const quicksand = Quicksand({ subsets: ["latin"] });

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className={quicksand.className}>
        <ThemeProvider>{children}</ThemeProvider>
      </body>
    </html>
  );
}
